
server:
  port: 8855


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_tools?useAffectedRows=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  # 指定mybatis全局配置文件中的相关配置项
  configuration:
    map-underscore-to-camel-case: true


election:
  # 取值，ManualAllocation: 通过人工选主  Mysql: 通过mysql选主
  algorithm: Mysql
  # 人工选择时，指定哪个机器
  manual-allocation.leader: 127.0.0.1

